# Generated by Django 2.2.4 on 2019-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('university', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=50)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('intro', models.CharField(max_length=300)),
                ('f1_visa_expertise', models.BooleanField(default=False)),
                ('f1_opt_expertise', models.BooleanField(default=False)),
                ('green_card_expertise', models.BooleanField(default=False)),
                ('h1B_expertise', models.BooleanField(default=False)),
                ('price_range', models.IntegerField(default=2)),
                ('rating', models.IntegerField(default=4)),
            ],
        ),
    ]
